#+STARTUP:indent
#+STYLE: <link rel="stylesheet" type="text/css" href="css/main.css"/>
#+STYLE: <link rel="stylesheet" type="text/css" href="css/lesson.css"/>

#+TITLE: Loopy JavaScript.
#+AUTHOR: Marc Scott

#+BEGIN_HTML
<div class=ribbon>
<a href="https://github.com/MarcScott/KS3_Curriculum">Fork me on GitHub</a>
</div>
#+END_HTML

* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:
** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:
** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:
** Try It:
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

* Two types of loops
- Sometimes when we're coding we like a program to perform an action over and over again.
- We use loops to do this for us.
- JavaScript has two types of loops - the =For= loop and the =While= loop.
* The While loop
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
- The While loop will repeat the instructions containined within it until some condition is met.
- An everyday example of a while loop mioght be something like.
#+BEGIN_SRC
WHILE WATER IS BELOW 100 DEGREES CELCIUS
    KEEP HEATING WATER
#+END_SRC
- This while loop will cause the water to heat up until it reaches 100 degrees, at which point it will stop heating.
- Another example of a while loop would be
#+BEGIN_SRC
WHILE BATH IS NOT FULL
    KEEP TAPS ON
#+END_SRC
** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:
- A while loop in JavaScript has fairly similar syntax to the if/else if/else statements.
#+BEGIN_SRC javascript
  while (condition)
  {
  //do something
  };
#+END_SRC
- Use the following code to get started.
#+BEGIN_SRC html
  <!DOCTYPE html>
  <html>
      <head>
          <title>MANIC BUTTON MASHER</title>
          <script type="text/javascript">
  
              counting = True;
              count = 0;
  
              while (counting === True)
              {
              document.write(count);
              }
  
                             
          </script>
      </head>
  <body>
  <p>How quickly can you push the button 20 times?</p>
  <input type="button" value="Click me" onclick="increaseScore()">
  </body>
  </html>
#+END_SRC
** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:
** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:
** Try It:
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

* Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Task
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:
To earn your fourth *Blue JavaScript Badge*, complete the tasks below. Once you have finished, ask your teacher to check your code to make sure it runs correctly.
